var html = '<div id="respond"><form  method="post" id="commentform">'
			+ '<div class="comment-login">请登录</div>'
			+ '<div class="comment-login">'
			+ '<ul>'
			+ '<li class="form-inline">'
			+ '<label>账号：</label>'
			+ '<input type="text" name="user" id="user" value="" tabindex="1" aria-required="true">'
			+ '</li>'
			+ '<li class="form-inline">'
			+ '<label>密码：</label>'
			+ '<input type="password" name="ps" id="ps" value="" tabindex="2" aria-required="true">'
			+ '</li>'
			+ '</ul>'
			+ '</div>'
			+ '<div class="comment-login"><input name="submit" type="button" id="save" onclick="loginIn()"  class="submitButton" tabindex="5" value="登录"></div>'
			+ '</form></div>';